// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmmBFHeowKYgUrw9-Sw-1vcomdJ1i_6wY',
    appId: '1:88257996285:web:ab7645caf0aa2f74ad6594',
    messagingSenderId: '88257996285',
    projectId: 'praktikum-ppb-if',
    authDomain: 'praktikum-ppb-if.firebaseapp.com',
    storageBucket: 'praktikum-ppb-if.appspot.com',
    measurementId: 'G-JNER6NCDXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYgm6zB19D1vXr4pPRHNTTFlmg09y_bBQ',
    appId: '1:88257996285:android:f1b4a6303b76e16dad6594',
    messagingSenderId: '88257996285',
    projectId: 'praktikum-ppb-if',
    storageBucket: 'praktikum-ppb-if.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBufN2XfnYx34FIxeS8DE1GbJzH_XD6h9g',
    appId: '1:88257996285:ios:f29df3a86716a8d4ad6594',
    messagingSenderId: '88257996285',
    projectId: 'praktikum-ppb-if',
    storageBucket: 'praktikum-ppb-if.appspot.com',
    iosBundleId: 'com.example.praktikum1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBufN2XfnYx34FIxeS8DE1GbJzH_XD6h9g',
    appId: '1:88257996285:ios:f29df3a86716a8d4ad6594',
    messagingSenderId: '88257996285',
    projectId: 'praktikum-ppb-if',
    storageBucket: 'praktikum-ppb-if.appspot.com',
    iosBundleId: 'com.example.praktikum1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmmBFHeowKYgUrw9-Sw-1vcomdJ1i_6wY',
    appId: '1:88257996285:web:df4a7b32c09b3bc4ad6594',
    messagingSenderId: '88257996285',
    projectId: 'praktikum-ppb-if',
    authDomain: 'praktikum-ppb-if.firebaseapp.com',
    storageBucket: 'praktikum-ppb-if.appspot.com',
    measurementId: 'G-2JZ5WCRD8R',
  );
}
